define:
  datapath: data/finetune
  # datapath: data
task:
  class: GermlineTask
  mode: train
  sequence_name: 'aligned_sequence'
  germline_name: 'germline'
  label_name: 'label'
  requires_tokenize: True
  tokenizer:
    class: Vocabulary
    path: data/vocab
    bos_token: <s>
    eos_token: </s>
    no_special_symbols: False
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 256
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      sort_samples: True
      path: ${datapath}/binder/mHER_H3.proc.adj.train.jsonl
    valid:
      class: JsonDataset
      sort_samples: False
      path: ${datapath}/binder/mHER_H3.proc.adj.valid.jsonl
    test:
      class: JsonDataset
      sort_samples: False
      path: ${datapath}/binder/mHER_H3.proc.adj.test.jsonl
  model:
    class: GermlineModel
    d_model: 768
    encoder:
      class: TransformerEncoder
      num_layers: 12
      d_model: 768
      n_head: 12
      embed_scale: ~
      dim_feedforward: 3072
      dropout: 0.1      
      attention_dropout: 0.1
      activation: 'gelu'
      learn_pos: True
      embed_layer_norm: True
    linear_probing:
      class: GermlineClassifierLayer
      num_labels: 2
      reduce_method: mean
      frozen_encoder: False
    path: best.pt
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 2e-5
        warmup_steps: 320
        total_steps: 50000
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_epochs: 20
    validate_interval_epoch: 1
    validate_interval_step: 1000
    assess_by: valid.roc
    save_best_k: 1
    save_last_k: 2
    no_best_avg: True
    early_stopping_tolerance: 5
    # save_model_dir: models/binder_ori
  generator:
    class: Generator
    is_regression: True
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
      mcc:
        class: MatthewsCorr
        is_labeling: False
      roc:
        class: ROC_AUC
        is_labeling: False
      f:
        class: F1
        target_label: 1
        is_labeling: False
env:
  device: cuda
  no_progress_bar: True
