define:
  datapath: data/finetune
  # datapath: data
task:
  class: GermlineTask
  mode: train
  sequence_name: 'sequence'
  germline_name: 'germline'
  label_name: 'Disease'
  target_label: 'SARS-COV-2'
  requires_tokenize: True
  tokenizer:
    class: Vocabulary
    path: data/vocab
    bos_token: <s>
    eos_token: </s>
    no_special_symbols: False
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 32
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      sort_samples: True
      path: ${datapath}/sars_germ_sm/cross_train_0_all.json
    valid:
      class: JsonDataset
      sort_samples: False
      path: ${datapath}/sars_germ_sm/cross_valid_0_all.json
  model:
    class: EvolutionModel
    d_model: 1280
    encoder:
      class: TransformerGermlineEncoder
      layer_type: 'transformer'
      layer_reduce_method: 'mean'
      concat_pos_embed: True
      normalize_before: True
      num_layers: 34
      d_model: 1280
      n_head: 20
      embed_scale: False
      embed_layer_norm: True
      dim_feedforward: 5120
      dropout: 0.1      
      attention_dropout: 0.1
      activation: 'gelu'
      learn_pos: True
    fusing_attn_type: 'x'
    remove_loaded_head: True
    linear_probing:
      class: GermlineClassifierLayer
      num_labels: 2
      reduce_method: mean
      frozen_encoder: False

    path: best.pt
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 3e-5
        warmup_steps: 1000
        total_steps: 500000
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
      update_frequency: 2
    max_epochs: 30
    max_steps: 500000
    validate_interval_epoch: 1
    validate_interval_step: 1000
    assess_by: valid.f
    save_best_k: 1
    save_last_k: 2
    no_best_avg: True
    early_stopping_tolerance: 10
  generator:
    class: Generator
    is_regression: True
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
      mcc:
        class: MatthewsCorr
        is_labeling: False
      roc:
        class: ROC_AUC
        is_labeling: False
      f:
        class: F1
        target_label: 1
        is_labeling: False
env:
  device: cuda
  no_progress_bar: True
  
