define:
  datapath: data/finetune
task:
  class: GermlineTask
  requires_tokenize: False
  mode: train
  sequence_name: 'sequence'
  germline_name: 'germline'
  label_name: 'label'
  tokenizer:
    class: ESMTokenizer
    model_name: &modelname esm1_t12_85M_UR50S
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 32
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      sort_samples: True
      path: ${datapath}/cell_germ/cross_train_0_all.json
    valid:
      class: JsonDataset
      sort_samples: False
      path: ${datapath}/cell_germ/cross_valid_0_all.json
  model:
    class: ESMPredictor
    model_name: *modelname
    d_model: 768
    layer_num: 12
    num_labels: 6
    reduce_method: mean
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 2e-5
        warmup_steps: 1000
        total_steps: 500000
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_epochs: 30
    validate_interval_epoch: 1
    validate_interval_step: 200
    assess_by: valid.acc
    save_best_k: 1
    save_last_k: 2
    no_best_avg: True
    early_stopping_tolerance: 5
  generator:
    class: Generator
    is_regression: False
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda
  no_progress_bar: True
