define:
  datapath: data/finetune
task:
  class: GermlineTask
  mode: train
  sequence_name: 'sequence'
  germline_name: 'germline'
  label_name: 'Disease'
  target_label: 'SARS-COV-2'
  requires_tokenize: False
  tokenizer:
    class: ESMTokenizer
    model_name: &modelname esm_msa1b_t12_100M_UR50S
  dataloader:
    train:
      class: StreamingDataLoader
      batch_size: 32
      num_workers: 1
    valid:
      class: StreamingDataLoader
      batch_size: 64
      num_workers: 0
  data:
    train:
      class: StreamingJsonDataset
      path: ${datapath}/disease_germ_2/cross_train_0_all.json
    valid:
      class: StreamingJsonDataset
      path: ${datapath}/disease_germ_2/cross_valid_0_all.json
  model:
    class: ESMMSAPredictor
    model_name: *modelname
    d_model: 768
    layer_num: 12
    num_labels: 2
    reduce_method: mean
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 3e-5
        warmup_steps: 1000
        total_steps: 500000
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_epochs: 30
    max_steps: 500000
    validate_interval_epoch: 1
    validate_interval_step: 100
    assess_by: valid.acc
    save_best_k: 1
    save_last_k: 2
    no_best_avg: True
    early_stopping_tolerance: 10
  generator:
    class: Generator
    is_regression: True
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
      mcc:
        class: MatthewsCorr
        is_labeling: False
      roc:
        class: ROC_AUC
        is_labeling: False
      f:
        class: F1
        target_label: 1
        is_labeling: False
env:
  device: cuda
  no_progress_bar: True
