define:
  datapath: data/finetune
task:
  class: GermlineTask
  mode: train
  sequence_name: 'sequence'
  germline_name: 'germline'
  label_name: 'label'
  requires_tokenize: True
  tokenizer:
    class: ESMTokenizer
    model_name: &modelname esm_msa1b_t12_100M_UR50S
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 32
    valid:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: JsonDataset
      sort_samples: True
      path: ${datapath}/toxicity_germ/cross_train_0_all.json
    valid:
      class: JsonDataset
      sort_samples: False
      path: ${datapath}/toxicity_germ/cross_valid_0_all.json
  model:
    class: ESMMSAPredictor
    model_name: *modelname
    d_model: 768
    layer_num: 12
    num_labels: 2
    reduce_method: mean
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 2e-5
        warmup_steps: 320
        total_steps: 50000
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_epochs: 20
    validate_interval_epoch: 1
    assess_by: acc
    save_best_k: 1
    save_last_k: 2
    no_best_avg: True
  generator:
    class: Generator
    is_regression: True
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
      mcc:
        class: MatthewsCorr
        is_labeling: False
      roc:
        class: ROC_AUC
        is_labeling: False
      f:
        class: F1
        target_label: 1
        is_labeling: False
env:
  device: cuda
